apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-test
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx:now
